version: '3.8'

services:
    db:
        image: mysql:5.7
        restart: always
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
        ports:
            - "3306:3306"
        volumes:
            - ./dixhuit_collections.sql:/docker-entrypoint-initdb.d/1.sql
            - db_data:/var/lib/mysql

    php:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "8080:${PORT:-80}"
        depends_on:
            - db
        volumes:
            - .:/var/www/html
        env_file:
            - .env

volumes:
    db_data: 